### PR TITLE
Allow for automation by accepting a refresh_token param

### LINKED ISSUE #1: Support a refresh token parameter to skip the OAuth redirect and allow automation
The first time a user approves the OAuth connection with Google there are usually three major pieces of response data:
- The access token.
- The expiration date of the access token.
- A refresh token which can be saved to get new access tokens when they expire.

AWSConsoleAuth should display the user's refresh token in the response so they can save it. Then if that refresh token is provided as a parameter it is used to get a new access token rather than requiring the user to go through the OAuth process. This means scripts can get a new AWS token without needing a browser or the user to intervene.

### PR DESCRIPTION
**Pull request by leavengood**
If the refresh token is provided, new OAuth access and ID tokens can be
requested without user intervention. This allows for automation.

To facilitate this, offline access is requested and the refresh token is
returned in the shell format responses.

Another tool can use these two pieces to automate the fetching of fresh
AWS keys and tokens each day.

Fixes #1.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/crewjam/awsconsoleauth/pull/6" target="_blank">ReviewNinja

**Comment by leavengood** [comment]
I figured the refresh token could be added to their shell's config, and we could add something to the makefile, or make another simple bash script to call this if that env variable exists.

**Comment by leavengood** [comment]
I've made some changes to address your concerns, and also cleaned up the shell exporting code a bit. One thing that is a bit annoying is that Google doesn't seem to return the refresh token on subsequent requests (at least where it has cached the fact that the user has authorized this app.) So users need to be sure to save it when they see it. Also user's need to keep it secure to keep people from impersonating them.

**Comment by crewjam** [comment]
:+1:

**Pull request merged**
